### ISSUE TITLE
run on chrX?

### ISSUE THREAD

**Issue by lkachuri** [getian107/PRScsx#18]
Dear Tian,

Is it possible to get PRS-CSx to run on the X chromosome? Is it just a matter of generating the LD blocks for chrX or are there technical reasons for restricting to the autosomes?

Thanks!

**Comment by getian107** [comment]
Dear Linda- We haven't incorporated X chromosomes into the PRS-CSx algorithm. Constructing PRS on X chromosomes might need special considerations (e.g. we might need to analyze males and females separately due to different dosages and the calculation of reference panels for X chromosomes may be different from autosomes which needs to be carefully validated).

**Comment by getian107** [comment]
Yes absolutely!
