### ISSUE TITLE
Applications in different populations

### ISSUE THREAD

**Issue by JhGodluc** [getian107/PRScsx#56]
hi, I might have a rather basic question. PRScsx is a great tool, and I believe that if I use one GWAS data from EUR population along with 1000G reference genotypes, and my target bim file is from the EAS population, I should be able to obtain a PRS for the EAS population. Is my understanding correct? If I cannot obtain GWAS data from the EAS population, can this approach still work?

**Comment by getian107** [comment]
Hi - If you only have GWAS summary statistics from one population, you can simply use PRS-CS. PRS-CSx is designed to integrate summary stats from two or more populations.

**Comment by JhGodluc** [comment]
Thank you very much for your reply. If so, it is more suitable for me to use PRScs? And can I select the 1000G EAS file for my target bim file?What factors primarily influence the accuracy of this strategy？

**Comment by getian107** [comment]
Yes, you can use PRScs, with a EUR reference panel and the target EAS bim file as the input. This is a cross-ancestry prediction so the accuracy may be lower than within EUR prediction. But since you only have a EUR GWAS, this is probably the best you can do. If you have an EAS GWAS in the future, you can use PRS-CSx to integrate EUR and EAS GWAS.

**Comment by JhGodluc** [comment]
Thank you for your reply, it's very important to me.
