### ISSUE TITLE
LD ref data for AMR 

### ISSUE THREAD

**Issue by joomango** [getian107/PRScsx#6]
Dear Tian,

Thank you for creating PRS-csx. I am very look forward to utilizing this method to improve the generalizability of PRS into admixed Americans and others. 

I noticed that LD ref data for EUR, EAS, AFR, and even SAS are available in PRS-csx but not for AMR. Could you please add AMR ref panel data to the package please? If not, could you at least provide any guideline explaining how I can build a ref panel data usable for PRS-csx? So I could make one for targeting AMR population from the 1000Genome project? I have Peruvian subjects as discovery cohort and this is def belongs to AMR superpopulation, not SAS or EUR, EAS, AFR... 

I very much appreciate your feedback and look forward to hearing from you at your earliest convenience. Your answer will be super helpful! Thanks, 

Yoonie

**Comment by getian107** [comment]
Hi Yoonie- Thanks for reaching out. We originally didn't add an AMR reference panel because it's an admixed population, in which the admixed proportion can vary between datasets, and we don't have precomputed cutoff points for LD blocks in AMR. Therefore an AMR reference panel will likely not match the LD in the GWAS sample very well. But since many people have asked, I am planning to build an AMR reference in the next couple of weeks, with the caveat that it might be less accurate than the reference for other populations. I will let you know when it is released.

**Comment by joomango** [comment]
Thanks for your prompt response! I understand the complexity and caveat of handling the admixed population for PRS computation. I will be very looking forward to the update. I appreciate your contribution!

**Comment by getian107** [comment]
AMR reference has been added. Let me know if you have questions.
